-- Table , 시퀀스 등 구조 정의
DROP SEQUENCE SQ_QNA;
DROP SEQUENCE SQ_FAQ;

CREATE SEQUENCE SQ_QNA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_FAQ START WITH 1 INCREMENT BY 1;

DROP TABLE TB_QNA CASCADE CONSTRAINT;
DROP TABLE TB_FAQ CASCADE CONSTRAINT;

CREATE TABLE TB_QNA
(
    QNO         NUMBER NOT NULL PRIMARY KEY,
    QUESTIONER    VARCHAR2(255),
    TITLE      VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

CREATE TABLE TB_FAQ
(
    QNO         NUMBER NOT NULL PRIMARY KEY,
    QUESTIONER    VARCHAR2(255),
    TITLE      VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);
